#!/bin/bash

echo "=========================================="
echo "🚀 Pushing to GitHub for Netlify Deployment"
echo "=========================================="
echo ""
echo "Repository: YUST777/Gifts-Toolkit"
echo "Branch: master"
echo ""
echo "Changes ready to push:"
echo "✅ Netlify configuration added"
echo "✅ Study project excluded (kept local)"
echo "✅ Clean deployment-ready codebase"
echo ""
echo "Pushing now..."
echo ""

git push origin master

if [ $? -eq 0 ]; then
    echo ""
    echo "=========================================="
    echo "✅ Successfully pushed to GitHub!"
    echo "=========================================="
    echo ""
    echo "Next steps:"
    echo "1. Go to https://app.netlify.com"
    echo "2. Click 'Add new site' → 'Import an existing project'"
    echo "3. Choose GitHub and select 'YUST777/Gifts-Toolkit'"
    echo "4. Netlify will auto-detect settings from netlify.toml"
    echo "5. Click 'Deploy site'"
    echo ""
    echo "📖 Read DEPLOYMENT_READY.md for detailed instructions"
    echo ""
else
    echo ""
    echo "=========================================="
    echo "❌ Push failed!"
    echo "=========================================="
    echo ""
    echo "You may need to authenticate. Try one of these:"
    echo ""
    echo "Option 1: GitHub CLI (recommended)"
    echo "  gh auth login"
    echo "  ./push_to_github.sh"
    echo ""
    echo "Option 2: SSH"
    echo "  git remote set-url origin git@github.com:YUST777/Gifts-Toolkit.git"
    echo "  ./push_to_github.sh"
    echo ""
    echo "Option 3: Personal Access Token"
    echo "  git push https://YOUR_TOKEN@github.com/YUST777/Gifts-Toolkit.git master"
    echo ""
fi

